# Generated by Django 3.2.7 on 2021-10-05 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistsfromnewreleases',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
