# Generated by Django 3.2.7 on 2021-10-06 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_artistsfromnewreleases_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('uri', models.CharField(max_length=100)),
                ('api_href', models.URLField()),
                ('spotify_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='NewReleases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('artists', models.ManyToManyField(related_name='new_release', to='api.Artist')),
            ],
        ),
        migrations.DeleteModel(
            name='ArtistsFromNewReleases',
        ),
    ]
